# Задание по лекциям 1.

- Не нужно использовать эффективные вычислительные алгоритмы. Нужно использовать те алгоритмы, что были представлены на лекции или практических занятиях. 
- Остальное как обычно: за "похожие" решения всем задействованным 0 баллов; если используете решение из открытого источника — обязательно вставьте ссылку; не удаляйте формулировки; не выкладывайте в открытый источник.
- Можно использовать `numpy.array` для матриц и матричной арифметики и `numpy.linalg` для подсчёта ранга и определителя, для вычисления обратной матрицы, решения СЛУ и т.п. То есть то, что вы уже реализовывали в прошлом семестре, ещё раз реализовывать необязательно. Более того, можно использовать в любом из *заданий по лекциям* функции, реализованные ранее в других *заданиях по лекциям*. Если возникнут сомнения, можно ли использовать ту или иную функцию — лучше сразу поинтересуйтесь у меня.

$\mathbb{R}^n$ — вещественнозначное пространство вектор-**столбцов**.

**(1 балл) Задание 1.** Реализовать функцию, принимающую на вход два набора 
$$
u = (u_1, \ldots, u_n),\ v = (v_1,\ldots,v_n)
$$
координат векторов (в стандартном базисе) из пространства $\mathbb{R}^n$, и выдающую 
- матрицу перехода от базиса $u$ к базису $v$, если оба этих набора являются базисами;
- None, иначе (альтернативный вариант — кидать исключение).

In [4]:
import numpy as np 
import scipy.linalg as sla

def transition(u, v):
    u = u.T
    v = v.T
    det_u = sla.det(u)
    det_v = sla.det(v)
    if det_u == 0 or det_v == 0: 
        return None
    else:
        return (np.dot(sla.inv(u), v))
    


assert np.allclose (transition(np.array([[1, 2, 1], [2, 3, 3], [3, 8, 2]]), np.array([[3, 5, 8], [5, 14, 13], [1, 9, 3]])), np.array([[-27., -71., -48.], [9., 20., 11.], [4., 12., 9.]]))
assert transition(np.array([[1, 2, 1], [2, 4, 2], [3, 8, 2]]), np.array([[3, 5, 8], [5, 14, 13], [1, 9, 3]])) == None

> Если на всход подается матрица записи вида: $u = np.array[[u_1], [u_2], ... ,[u_n]]$, где $[u_i]$ содержит координаты вектора $u_i$, то для получения ответа нам надо ее транспонировать, чтобы координаты векторов располагались вертикально.

> Если на вход подается матрица, координаты векторов которой сразу расположены вертикально, то операции транспонирования не нужны.
$$
\begin{pmatrix}
| & | & ... & |\\
u_1 & u_2 & ... & u_n\\
| & | & ... & |
\end{pmatrix}
$$ 

> Я рассмотрела первый вариант, мне кажется так проще задавать матрицу, зная вектора, потому что их так легче записать.

**(1 балл) Задание 2.** Реализовать функцию, принимающую на вход матрицу $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ (в стандартном базисе) и набор координат $u = (u_1,\ldots,u_n)$ вектор-столбцов, и выдающую 
- матрицу оператора $\varphi$ в базисе $u$, если $u$ является базисом;
- None, иначе (альтернативный вариант — кидать исключение).

In [6]:
import numpy as np 
import scipy.linalg as sla

def lin_operator(A, u):        
    #u = u.T
    det_u = sla.det(u)
    if det_u == 0: 
        return None
    else:
        reverse_u = sla.inv(u)
        trans_matrix = np.dot(reverse_u, A).dot(u)
        return (trans_matrix)

    
    
assert np.allclose (lin_operator(np.array([[1., 2., 0., 1.], [3., 0., -1., 1.], [2., 5., 3., 1.], [1., 2., 1., 3.]]), np.array([[1., 1., 1., 1.], [0., 1., 1., 1.], [0., 0., 1., 1.], [0., 0., 0., 1.]])), np.array([[-2., 0., 1., 1.], [1., -4., -8., -8.], [1., 4., 6., 4.], [1., 3., 4., 7.]]))
assert lin_operator(np.array([[1., 0.], [0., 2.]]), np.array([[-2, 4], [-1, 2]])) == None

> Записть матрицы так же идет по векторам, иначе нужно транспонировать атрицу $u$

**(1.5 балла) Задание 3.** Реализовать функции, которые по данной матрице $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ в стандартном базисе, выдадут:

- базис образа $\varphi$ (0.5 балла)
- базис ядра $\varphi$ (0.75 балла)
- размерности ядра и образа $\varphi$ (0.25 балла)

In [29]:

import numpy as np 
import scipy.linalg as sla
from scipy import linalg
import sympy

# один из способов найти базис оболочки оператора
def image_fun(A):
    A = A.T
    _, indx = sympy.Matrix(A).T.rref()
    indx = np.array(indx)
    return(A[indx])


assert np.allclose (image_fun(np.array([[1., 0., 0., 0.], [0., 0., 0., 0.], [1., 0., 0., 0.], [0., 0., 0., 1.]])), np.array([[1, 0, 1, 0], [0, 0, 0, 1]]))
assert np.allclose (image_fun(np.array([[1, 0, 1], [1, 1, 2], [0, 2, 2]])), np.array([[1, 1, 0], [0, 1, 2]]))
assert np.allclose (image_fun(np.array([[4, -5, 2], [5,-7, 3], [6, -9, 4]])), np.array([[4, 5, 6], [-5,-7, -9]]))

    
#находнеие размерноти ядра и образа оператора
def dimension_fun(A):
    dim_im = np.linalg.matrix_rank(A)
    size_r = np.shape(A)[1]
    dim_ker = size_r - dim_im
    return (dim_im, dim_ker)


assert np.allclose (dimension_fun(np.array([[4, 5, 6], [-5,-7, -9], [2, 3, 4]])), (2, 1))
assert np.allclose (dimension_fun(np.array([[1., 0., 0., 0.], [0., 0., 0., 0.], [1., 0., 0., 0.], [0., 0., 0., 1.]])), (2, 2))
assert np.allclose (dimension_fun(np.array([[1, 0, 1], [1, 1, 2], [0, 2, 2]])), (2, 1))




In [30]:
import numpy as np 


def triangular_view(A_matrix):
    size = A_matrix.shape
    E = np.eye(size[1])
    new_matrix = np.concatenate((A_matrix.T, E), axis=1)
    new_size = new_matrix.shape
    n = new_size[0]
    for t in range(n):
        if new_matrix[t][t] == 0:
            i = t + 1
            while i < n and new_matrix[t][t] == 0:
                if new_matrix[i][t] != 0:
                    for j in range(2 * n):
                        new_matrix[t][j] += new_matrix[i][j]
                i += 1
        if new_matrix[t][t] != 0:
            for i in range(t + 1, n):
                c = new_matrix[i][t] / new_matrix[t][t]
                for j in range(t, 2 * n):
                    new_matrix[i][j] -= new_matrix[t][j] * c
    return new_matrix


def free_view(A):
    new_matrix = triangular_view(A)
    size = A.shape
    ker = np.zeros(size[0])
    im = np.zeros(size[0])
    A_mat = np.array(A).astype(np.float64)
    B_mat = np.array(A).astype(np.float64)
    for i in range(size[0]):
        for j in range(size[1]):
            A_mat[i][j] = new_matrix[i][j]

    for i in range(size[0]):
        for j in range(size[1]):
            B_mat[i][j] = new_matrix[i][j+size[1]]
    i = 0
    for row in A_mat:
        if row.any() == 0:
            ker = np.vstack((ker, B_mat[i]))
        if row.any() != 0:
            im = np.vstack((im, row))
        i += 1
    im = np.delete(im,(0), axis = 0)
    ker = np.delete(ker, (0), axis=0)
    return (im, ker)


    
if __name__ == '__main__':
    A = np.array([[1, 1, 0], [0, 1, 2], [1, 2, 2]])
    im, ker = free_view(A)
    print ('базис образа  𝜑:', '\n', im)
    print ('базис ядра  𝜑:', '\n', ker)

базис образа  𝜑: 
 [[1. 0. 1.]
 [0. 1. 1.]]
базис ядра  𝜑: 
 [[ 2. -2.  1.]]


> Релизован алгоритм Чуркина.

**(1 балл) Задание 4.** Реализовать функцию, принимающую на вход матрицу $A$ линейного оператора $\varphi: \mathbb{R}^n \to \mathbb{R}^n$ (в стандартном базисе) и набор координат $u = (u_1,\ldots,u_k),\ k\le n$ вектор-столбцов, и выдающую 
- True, если линейная оболочка векторов $(u_1,\ldots, u_k)$ является $\varphi$-инвариантным подпространством.
- False, иначе.